// ignore_for_file: constant_identifier_names

/// Country Code Enum
/// http://en.wikipedia.org/wiki/ISO_3166-1
enum CountryCode {
  AD("AD", "Andorra", "AND"),
  AE("AE", "United Arab Emirates", "ARE"),
  AF("AF", "Afghanistan", "AFG"),
  AG("AG", "Antigua and Barbuda", "ATG"),
  AI("AI", "Anguilla", "AIA"),
  AL("AL", "Albania", "ALB"),
  AM("AM", "Armenia", "ARM"),
  AO("AO", "Angola", "AGO"),
  AQ("AQ", "Antarctica", "ATA"),
  AR("AR", "Argentina", "ARG"),
  AS("AS", "American Samoa", "ASM"),
  AT("AT", "Austria", "AUT"),
  AU("AU", "Australia", "AUS"),
  AW("AW", "Aruba", "ABW"),
  AX("AX", "\u212Bland Islands", "ALA"),
  AZ("AZ", "Azerbaijan", "AZE"),
  BA("BA", "Bosnia and Herzegovina", "BIH"),
  BB("BB", "Barbados", "BRB"),
  BD("BD", "Bangladesh", "BGD"),
  BE("BE", "Belgium", "BEL"),
  BF("BF", "Burkina Faso", "BFA"),
  BG("BG", "Bulgaria", "BGR"),
  BH("BH", "Bahrain", "BHR"),
  BI("BI", "Burundi", "BDI"),
  BJ("BJ", "Benin", "BEN"),
  BL("BL", "Saint Barth\u00E9lemy", "BLM"),
  BM("BM", "Bermuda", "BMU"),
  BN("BN", "Brunei Darussalam", "BRN"),
  BO("BO", "Plurinational State of Bolivia", "BOL"),
  BQ("BQ", "Bonaire, Sint Eustatius and Saba", "BES"),
  BR("BR", "Brazil", "BRA"),
  BS("BS", "Bahamas", "BHS"),
  BT("BT", "Bhutan", "BTN"),
  BV("BV", "Bouvet Island", "BVT"),
  BW("BW", "Botswana", "BWA"),
  BY("BY", "Belarus", "BLR"),
  BZ("BZ", "Belize", "BLZ"),
  CA("CA", "Canada", "CAN"),
  CC("CC", "Cocos Islands", "CCK"),
  CD("CD", "The Democratic Republic of the Congo", "COD"),
  CF("CF", "Central African Republic", "CAF"),
  CG("CG", "Congo", "COG"),
  CH("CH", "Switzerland", "CHE"),
  CI("CI", "C\u00F4te d'Ivoire", "CIV"),
  CK("CK", "Cook Islands", "COK"),
  CL("CL", "Chile", "CHL"),
  CM("CM", "Cameroon", "CMR"),
  CN("CN", "China", "CHN"),
  CO("CO", "Colombia", "COL"),
  CR("CR", "Costa Rica", "CRI"),
  CU("CU", "Cuba", "CUB"),
  CV("CV", "Cape Verde", "CPV"),
  CW("CW", "Cura\u00E7ao", "CUW"),
  CX("CX", "Christmas Island", "CXR"),
  CY("CY", "Cyprus", "CYP"),
  CZ("CZ", "Czech Republic", "CZE"),
  DE("DE", "Germany", "DEU"),
  DJ("DJ", "Djibouti", "DJI"),
  DK("DK", "Denmark", "DNK"),
  DM("DM", "Dominica", "DMA"),
  DO("DO", "Dominican Republic", "DOM"),
  DZ("DZ", "Algeria", "DZA"),
  EC("EC", "Ecuador", "ECU"),
  EE("EE", "Estonia", "EST"),
  EG("EG", "Egypt", "EGY"),
  EH("EH", "Western Sahara", "ESH"),
  ER("ER", "Eritrea", "ERI"),
  ES("ES", "Spain", "ESP"),
  ET("ET", "Ethiopia", "ETH"),
  FI("FI", "Finland", "FIN"),
  FJ("FJ", "Fiji", "FJI"),
  FK("FK", "Falkland Islands", "FLK"),
  FM("FM", "Federated States of Micronesia", "FSM"),
  FO("FO", "Faroe Islands", "FRO"),
  FR("FR", "France", "FRA"),
  GA("GA", "Gabon", "GAB"),
  GB("GB", "United Kingdom", "GBR"),
  GD("GD", "Grenada", "GRD"),
  GE("GE", "Georgia", "GEO"),
  GF("GF", "French Guiana", "GUF"),
  GG("GG", "Guemsey", "GGY"),
  GH("GH", "Ghana", "GHA"),
  GI("GI", "Gibraltar", "GIB"),
  GL("GL", "Greenland", "GRL"),
  GM("GM", "Gambia", "GMB"),
  GN("GN", "Guinea", "GIN"),
  GP("GP", "Guadeloupe", "GLP"),
  GQ("GQ", "Equatorial Guinea", "GNQ"),
  GR("GR", "Greece", "GRC"),
  GS("GS", "South Georgia and the South Sandwich Islands", "SGS"),
  GT("GT", "Guatemala", "GTM"),
  GU("GU", "Guam", "GUM"),
  GW("GW", "Guinea-Bissau", "GNB"),
  GY("GY", "Guyana", "GUY"),
  HK("HK", "Hong Kong", "HKG"),
  HM("HM", "Heard Island and McDonald Islands", "HMD"),
  HN("HN", "Honduras", "HND"),
  HR("HR", "Croatia", "HRV"),
  HT("HT", "Haiti", "HTI"),
  HU("HU", "Hungary", "HUN"),
  ID("ID", "Indonesia", "IDN"),
  IE("IE", "Ireland", "IRL"),
  IL("IL", "Israel", "ISR"),
  IM("IM", "Isle of Man", "IMN"),
  IN("IN", "India", "IND"),
  IO("IO", "British Indian Ocean Territory", "IOT"),
  IQ("IQ", "Iraq", "IRQ"),
  IR("IR", "Islamic Republic of Iran", "IRN"),
  IS("IS", "Iceland", "ISL"),
  IT("IT", "Italy", "ITA"),
  JE("JE", "Jersey", "JEY"),
  JM("JM", "Jamaica", "JAM"),
  JO("JO", "Jordan", "JOR"),
  JP("JP", "Japan", "JPN"),
  KE("KE", "Kenya", "KEN"),
  KG("KG", "Kyrgyzstan", "KGZ"),
  KH("KH", "Cambodia", "KHM"),
  KI("KI", "Kiribati", "KIR"),
  KM("KM", "Comoros", "COM"),
  KN("KN", "Saint Kitts and Nevis", "KNA"),
  KP("KP", "Democratic People's Republic of Korea", "PRK"),
  KR("KR", "Republic of Korea", "KOR"),
  KW("KW", "Kuwait", "KWT"),
  KY("KY", "Cayman Islands", "CYM"),
  KZ("KZ", "Kazakhstan", "KAZ"),
  LA("LA", "Lao People's Democratic Republic", "LAO"),
  LB("LB", "Lebanon", "LBN"),
  LC("LC", "Saint Lucia", "LCA"),
  LI("LI", "Liechtenstein", "LIE"),
  LK("LK", "Sri Lanka", "LKA"),
  LR("LR", "Liberia", "LBR"),
  LS("LS", "Lesotho", "LSO"),
  LT("LT", "Lithuania", "LTU"),
  LU("LU", "Luxembourg", "LUX"),
  LV("LV", "Latvia", "LVA"),
  LY("LY", "Libya", "LBY"),
  MA("MA", "Morocco", "MAR"),
  MC("MC", "Monaco", "MCO"),
  MD("MD", "Republic of Moldova", "MDA"),
  ME("ME", "Montenegro", "MNE"),
  MF("MF", "Saint Martin", "MAF"),
  MG("MG", "Madagascar", "MDG"),
  MH("MH", "Marshall Islands", "MHL"),
  MK("MK", "The former Yugoslav Republic of Macedonia", "MKD"),
  ML("ML", "Mali", "MLI"),
  MM("MM", "Myanmar", "MMR"),
  MN("MN", "Mongolia", "MNG"),
  MO("MO", "Macao", "MAC"),
  MP("MP", "Northern Mariana Islands", "MNP"),
  MQ("MQ", "Martinique", "MTQ"),
  MR("MR", "Mauritania", "MRT"),
  MS("MS", "Montserrat", "MSR"),
  MT("MT", "Malta", "MLT"),
  MU("MU", "Mauritius", "MUS"),
  MV("MV", "Maldives", "MDV"),
  MW("MW", "Malawi", "MWI"),
  MX("MX", "Mexico", "MEX"),
  MY("MY", "Malaysia", "MYS"),
  MZ("MZ", "Mozambique", "MOZ"),
  NA("NA", "Namibia", "NAM"),
  NC("NC", "New Caledonia", "NCL"),
  NE("NE", "Niger", "NER"),
  NF("NF", "Norfolk Island", "NFK"),
  NG("NG", "Nigeria", "NGA"),
  NI("NI", "Nicaragua", "NIC"),
  NL("NL", "Netherlands", "NLD"),
  NO("NO", "Norway", "NOR"),
  NP("NP", "Nepal", "NPL"),
  NR("NR", "Nauru", "NRU"),
  NU("NU", "Niue", "NIU"),
  NZ("NZ", "New Zealand", "NZL"),
  OM("OM", "Oman", "OMN"),
  PA("PA", "Panama", "PAN"),
  PE("PE", "Peru", "PER"),
  PF("PF", "French Polynesia", "PYF"),
  PG("PG", "Papua New Guinea", "PNG"),
  PH("PH", "Philippines", "PHL"),
  PK("PK", "Pakistan", "PAK"),
  PL("PL", "Poland", "POL"),
  PM("PM", "Saint Pierre and Miquelon", "SPM"),
  PN("PN", "Pitcairn", "PCN"),
  PR("PR", "Puerto Rico", "PRI"),
  PS("PS", "Occupied Palestinian Territory", "PSE"),
  PT("PT", "Portugal", "PRT"),
  PW("PW", "Palau", "PLW"),
  PY("PY", "Paraguay", "PRY"),
  QA("QA", "Qatar", "QAT"),
  RE("RE", "R\u00E9union", "REU"),
  RO("RO", "Romania", "ROU"),
  RS("RS", "Serbia", "SRB"),
  RU("RU", "Russian Federation", "RUS"),
  RW("RW", "Rwanda", "RWA"),
  SA("SA", "Saudi Arabia", "SAU"),
  SB("SB", "Solomon Islands", "SLB"),
  SC("SC", "Seychelles", "SYC"),
  SD("SD", "Sudan", "SDN"),
  SE("SE", "Sweden", "SWE"),
  SG("SG", "Singapore", "SGP"),
  SH("SH", "Saint Helena, Ascension and Tristan da Cunha", "SHN"),
  SI("SI", "Slovenia", "SVN"),
  SJ("SJ", "Svalbard and Jan Mayen", "SJM"),
  SK("SK", "Slovakia", "SVK"),
  SL("SL", "Sierra Leone", "SLE"),
  SM("SM", "San Marino", "SMR"),
  SN("SN", "Senegal", "SEN"),
  SO("SO", "Somalia", "SOM"),
  SR("SR", "Suriname", "SUR"),
  SS("SS", "South Sudan", "SSD"),
  ST("ST", "Sao Tome and Principe", "STP"),
  SV("SV", "El Salvador", "SLV"),
  SX("SX", "Sint Maarten", "SXM"),
  SY("SY", "Syrian Arab Republic", "SYR"),
  SZ("SZ", "Swaziland", "SWZ"),
  TC("TC", "Turks and Caicos Islands", "TCA"),
  TD("TD", "Chad", "TCD"),
  TF("TF", "French Southern Territories", "ATF"),
  TG("TG", "Togo", "TGO"),
  TH("TH", "Thailand", "THA"),
  TJ("TJ", "Tajikistan", "TJK"),
  TK("TK", "Tokelau", "TKL"),
  TL("TL", "Timor-Leste", "TLS"),
  TM("TM", "Turkmenistan", "TKM"),
  TN("TN", "Tunisia", "TUN"),
  TO("TO", "Tonga", "TON"),
  TR("TR", "Turkey", "TUR"),
  TT("TT", "Trinidad and Tobago", "TTO"),
  TV("TV", "Tuvalu", "TUV"),
  TW("TW", "Taiwan, Province of China", "TWN"),
  TZ("TZ", "United Republic of Tanzania", "TZA"),
  UA("UA", "Ukraine", "UKR"),
  UG("UG", "Uganda", "UGA"),
  UM("UM", "United States Minor Outlying Islands", "UMI"),
  US("US", "United States", "USA"),
  UY("UY", "Uruguay", "URY"),
  UZ("UZ", "Uzbekistan", "UZB"),
  VA("VA", "Holy See", "VAT"),
  VC("VC", "Saint Vincent and the Grenadines", "VCT"),
  VE("VE", "Bolivarian Republic of Venezuela", "VEN"),
  VG("VG", "British Virgin Islands", "VGB"),
  VI("VI", "Virgin Islands, U.S.", "VIR"),
  VN("VN", "Viet Nam", "VNM"),
  VU("VU", "Vanuatu", "VUT"),
  WF("WF", "Wallis and Futuna", "WLF"),
  WS("WS", "Samoa", "WSM"),
  XK("XK", "Kosovo", "UNK"),
  YE("YE", "Yemen", "YEM"),
  YT("YT", "Mayotte", "MYT"),
  ZA("ZA", "South Africa", "ZAF"),
  ZM("ZM", "Zambia", "ZMB"),
  ZW("ZW", "Zimbabwe", "ZWE");

  final String countryCode;
  final String countryName;
  final String countryCodeIso;
  const CountryCode(this.countryCode, this.countryName, this.countryCodeIso);

  static final Map<String, CountryCode> by2code = {};
  static final Map<String, CountryCode> by3code = {};

  static CountryCode? countryByCode(String code) {
    if (by2code.isEmpty) {
      for (CountryCode country in CountryCode.values) {
        by2code[country.countryCode] = country;
      }
    }

    if (by3code.isEmpty) {
      for (CountryCode country in CountryCode.values) {
        by3code[country.countryCodeIso] = country;
      }
    }

    CountryCode? info;
    try {
      if (code.length == 3) {
        info = by3code[code];
      } else if (code.length == 2) {
        info = by2code[code];
      }
    } catch (e) {
      info = null;
    }

    return info;
  }
}
